name: Demo

on: 
  workflow_dispatch:
    inputs:
      areYouFeelingGood:
        description: "Are you feeling good ?"
        type: boolean
        default: false

jobs:
  Greeting:
      runs-on: ubuntu-latest
      steps:
          - name: Say Hello
            run: echo "We are learning Github Actions"
  job2:
      runs-on: ubuntu-latest
      needs: [Greeting]
      steps:
        - name: Step2 
          run: echo "This is step2"
        - name: Step3
          if: ${{ inputs.areYouFeelingGood }}
          run: echo "I a"
          
      
    
