name: Demo

on:
#Webhook Event
  push:
    branches:
      - main
      - Task/*
      - feat/*
  pull_request:
    branches:
      - main
  issues:
    types: 
      - closed
      - opened
      
  # Schedule event
  schedule:
    - cron: 0 0 * * * 
    - cron: 0 0 * * 0
    
  # Manual event
  workflow_dispatch:
    inputs:
      areYouFeelingGood:
        description: "Are you feeling good ?"
        type: boolean
        default: false
env:
  MY_VAR: priti
  

jobs:
  Greeting:
      runs-on: ubuntu-latest
      steps:
          - name: Say Hello
            run: echo "We are learning Github Actions"
  job2:
      runs-on: ubuntu-latest
      needs: [Greeting]
      steps:
        - name: Step2 
          run: echo "This is step2"
        - name: Step3
          if: ${{ inputs.areYouFeelingGood }}
          run: echo "Great"
        - name: Step4
          run: echo ${{env.MY_VAR}}
          
      
    
